locale: fr_FR
name: "ESSARRAJ Fouad"
title: "ESSARRAJ Fouad"
description: "Ingénieur et formateur Web"
baseurl: ''
include: ["_pages"]
permalink: /:title/
url : https://essarrajfouad.com

# Collections
collections:
  tags:
    output: true
    permalink: tags/:path/
  services:
    output: true
    permalink: /services/:name/
  projectNatures:
    output: true
    permalink: /natures-projets/:title/
  projects:
    output: true
    permalink: /projets/:title/
  skills:
    output: true
    permalink: /compétences/:title/
  technologies:
    output: true
    permalink: /services/:name/
  questions:
    output: false

# Authors
authors:
  essarraj:
    name: ESSARRAJ
    display_name: Fouad
    gravatar: e1cd7eaea3fcf6c1e320fd9378713d4f
    email: essarraj.fouad@gmail.com
    web: https://www.essarrajfouad.com
    description: "J'aide les étudiants, élèves ingénieur et stagiaires à développer leurs compétences en développement d’application."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /blog/page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
